# Generated by Django 2.2 on 2020-06-04 11:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('addre', models.CharField(max_length=200)),
                ('default_address', models.BooleanField()),
                ('phone', models.CharField(max_length=11)),
                ('receiver', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'adderss',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=20)),
                ('bsotry', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
                ('type_num', models.IntegerField()),
            ],
            options={
                'db_table': 'goods_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('member_level', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('uimg', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrdrGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField(auto_created=True)),
                ('gid', models.IntegerField()),
                ('goodnum', models.IntegerField()),
                ('goodprice', models.IntegerField()),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordr_goods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('pay_mothod', models.SmallIntegerField(choices=[('1', '货到付款'), ('2', '支付宝')], default=2)),
                ('total_count', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待评价')], default=1)),
                ('transit_price', models.SmallIntegerField(choices=[(1, '申通快递'), (2, '圆通快递'), (3, '韵达快递')], default=1)),
                ('create_time', models.DateField()),
                ('aid', models.ForeignKey(db_column='aid', on_delete=django.db.models.deletion.CASCADE, to='App.Address')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_info',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=20)),
                ('gtitle', models.CharField(max_length=200)),
                ('gdescription', models.CharField(max_length=200)),
                ('gprice', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=1)),
                ('sales', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(0, '无'), (1, '新品'), (2, '精品'), (3, '热销')], default=0)),
                ('gsize', models.CharField(max_length=10)),
                ('gcolor', models.SmallIntegerField(choices=[(0, '白色'), (1, '黑色'), (2, '灰色'), (3, '红色')], default=0)),
                ('is_del', models.BooleanField(default=True)),
                ('bid', models.ForeignKey(blank=True, db_column='bid', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Brand')),
                ('tid', models.ForeignKey(blank=True, db_column='tid', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.GoodsType')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='uid',
            field=models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
