# Generated by Django 2.2 on 2020-03-25 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('addre', models.CharField(max_length=200)),
                ('default_address', models.BooleanField()),
            ],
            options={
                'db_table': 'adderss',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
                ('type_num', models.IntegerField()),
            ],
            options={
                'db_table': 'goods_type',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('pay_mothod', models.SmallIntegerField(choices=[('1', '货到付款'), ('2', '支付宝')], default=2)),
                ('total_count', models.IntegerField(default=1, max_length=9999)),
                ('total_price', models.IntegerField()),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待评价')], default=1)),
                ('transit_price', models.SmallIntegerField(choices=[(1, '申通快递'), (2, '圆通快递'), (3, '韵达快递')], default=1)),
                ('create_time', models.DateField()),
                ('aid', models.ForeignKey(db_column='aid', on_delete=django.db.models.deletion.CASCADE, to='App.Address')),
            ],
            options={
                'db_table': 'order_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('member_level', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('uimg', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='OrdrGoods',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('goodnum', models.IntegerField()),
                ('goodprice', models.IntegerField()),
                ('oid', models.ForeignKey(db_column='oid', on_delete=django.db.models.deletion.CASCADE, to='App.OrderInfo')),
            ],
            options={
                'db_table': 'ordr_goods',
            },
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=20)),
                ('gtitle', models.CharField(max_length=200)),
                ('gprice', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=1)),
                ('sales', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(0, '无'), (1, '新品'), (2, '精品'), (3, '热销')], default=0)),
                ('gsize', models.CharField(max_length=10)),
                ('gcolor', models.SmallIntegerField(choices=[(0, '白色'), (1, '黑色'), (2, '灰色'), (3, '红色')], default=0)),
                ('tid', models.ForeignKey(blank=True, db_column='tid', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.GoodsType')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='uid',
            field=models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
    ]
